customCommands:
  - key: '<c-c>'
    context: 'global'
    description: 'Gitmojiでコミット'
    prompts:
      - type: 'menu'
        title: 'Gitmojiを選択'
        key: 'Gitmoji'
        options:
          - name: '🎉 初回コミット'
            value: '🎉'
          - name: '✨ 新機能追加'
            value: '✨'
          - name: '🐛 バグ修正'
            value: '🐛'
          - name: '♻️ リファクタリング'
            value: '♻️'
          - name: '📝 ドキュメント'
            value: '📝'
          - name: '🔖 バージョン・リリース'
            value: '🔖'
          - name: '🎨 コード整形・構造改善'
            value: '🎨'
          - name: '🔧 設定ファイル変更'
            value: '🔧'
          - name: '🗑️ 削除'
            value: '🗑️'
      - type: 'input'
        title: 'コミットメッセージ'
        key: 'CommitMessage'
    command: 'git commit -m {{ printf "%s %s" .Form.Gitmoji .Form.CommitMessage | quote }}'
    loadingText: 'コミット中...'
